name: HIFINI-Auto-Checkin

on:
  workflow_dispatch:
  schedule:
    # UTC+8 00:00
    # - cron: "0 16 * * *"
    # UTC+8 08:00
    - cron: "18 07 * * *"

jobs:
  checkin:
    runs-on: ubuntu-latest
    environment: HIFINI
    env:
      COOKIE: ${{ secrets.COOKIE }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js latest.
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Checkin
        shell: bash
        run: |
          node main.js
